-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(30*(C.DAILY_FEE*(100-DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE= P.CAR_TYPE
WHERE (C.CAR_TYPE='세단' OR C.CAR_TYPE='SUV')
    AND P.DURATION_TYPE='30일 이상'
    AND C.CAR_ID NOT IN (
        SELECT H.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.END_DATE >='2022-11-01' AND H.START_DATE <='2022-11-30'
    )
    AND 30*(C.DAILY_FEE*(100-DISCOUNT_RATE)/100)>=500000 AND 30*(C.DAILY_FEE*(100-DISCOUNT_RATE)/100)<2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID;