-- 코드를 작성해주세요
SELECT T.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE T JOIN ITEM_INFO I
ON T.PARENT_ITEM_ID=I.ITEM_ID
JOIN ITEM_INFO C
ON T.ITEM_ID = C.ITEM_ID
WHERE I.RARITY='RARE'
ORDER BY C.ITEM_ID  DESC;