-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH 
FROM FISH_INFO I JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
JOIN(
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
ON I.LENGTH=M.LENGTH AND I.FISH_TYPE=M.FISH_TYPE
ORDER BY I.ID;