SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) F
JOIN FISH_INFO I ON F.FISH_TYPE=I.FISH_TYPE AND F.LENGTH=I.LENGTH
JOIN FISH_NAME_INFO N ON I.FISH_TYPE=N.FISH_TYPE
ORDER BY I.ID;