-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE PRICE=(
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE F.CATEGORY=CATEGORY
) AND (CATEGORY='과자' OR CATEGORY='국' OR CATEGORY ='김치' OR CATEGORY='식용유')
ORDER BY MAX_PRICE DESC